{{- if and .Values.mssql.enabled (not .Values.mssql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql-helm.saSecretName" . }}
  labels:
    {{- include "mssql-helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.mssql.auth.saPasswordKey }}: {{ .Values.mssql.auth.saPassword | quote }}
{{- end }}
