{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mssql-helm.fullname" . }}-operator
  labels:
    {{- include "mssql-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mssql-helm.name" . }}
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mssql-helm.name" . }}
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "mssql-helm.operatorServiceAccountName" . }}
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INTERVAL_SECONDS
              value: {{ .Values.operator.reconcileIntervalSeconds | quote }}
            - name: EXECUTOR_IMAGE
              value: "{{ .Values.operator.executor.image }}:{{ .Values.operator.executor.tag }}"
            - name: EXECUTOR_PULL_POLICY
              value: {{ .Values.operator.executor.pullPolicy | quote }}
{{- end }}
